---
title: "Exercicio_limpeza_dados"
author: "Abioluz Robson Behrend"
date: "2023-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Biblioteca para gráfico de correlação
# library(corrgram)
#library(corrgram)

# Biblioteca para modelos de ML
# install.packages('e1071')
#library(e1071)

```

# Tratamento e Lipeza de dados

---
*Dados do Projeto:*

Aparência: sol, nublado, chuva
Temperatura: -130 ~ 130F
Umidade: 0 ~ 100
Jogar: sim/não
---


```{r}
dados = read.csv('tempo.csv', sep=';', stringsAsFactors=T)
head(dados)
summary(dados)

# Ver valores faltantes

dados[!complete.cases(dados),]

plot(dados)
```


## Tratar as variáveis categóricas

```{r}
aparencia = table(dados$Aparencia)
barplot(aparencia, main='Aparência', xlab='Aparências')
print(summary(dados$Aparencia))

# Ver categorias
unique(dados$Aparencia)

# ver dados NA ou vazio
dados[is.na(dados$Aparencia) | dados$Aparencia=='',]


# Trocar os dados de menos pela moda. No caso será chuva
dados[dados$Aparencia == 'menos',]$Aparencia = 'chuva'

# Remover o sumário excluido
dados$Aparencia = factor(dados$Aparencia)

summary(dados$Aparencia)

aparencia2 = table(dados$Aparencia)
barplot(aparencia2, main='Aparência tratada', xlab='Aparências')

```

```{r}
vento = table(dados$Vento)
barplot(vento, main='Vento', xlab='vento')

print(summary(dados$Vento))

# ver dados únicos
unique(dados$Vento)

# Ver valores NA ou em Brancos
dados[is.na(dados$Vento) | dados$Vento == '',]

# Atribuir moda ao valor em branco
dados[dados$Vento == '',]$Vento = 'FALSO'

# Remover sumário em branco
dados$Vento = factor(dados$Vento)

# Verificar alterações
print(summary(dados$Vento))
vento2 = table(dados$Vento)
barplot(vento2, main='Vento2', xlab='vento')


```
```{r}
jogar = table(dados$Jogar)
jogar
barplot(jogar, main='Jogar')
summary(dados$Jogar)

# Verificar valores únicos
unique(dados$Jogar)

# Verificar valores vazio ou NA
dim(dados[is.na(dados$Jogar) | dados$Jogar == '',])



```

## Tratamento de dados numéricos


```{r}
summary(dados$Temperatura)
outlies = boxplot(dados$Temperatura, main='Temperatura', ylab='Temperatura em ºF')
hist(dados$Temperatura, main='Temperatura', xlab='Temperatura em ºF')

# Verificar dados fora do escopo (outlies)

dados[dados$Temperatura < -130 | dados$Temperatura > 130,]
outlies$out

# Obter a mediana
mediana = median(dados$Temperatura, na.rm=T)
mediana

dados$Temperatura

# Cuidado! 
# dados[dados$Temperatura <-130 | >> isso atribui o valor ao invés de fazer a operação lógica
# Para corrigir é necessário afaztar o "<" do "-" com um espaço
# dados[dados$Temperatura < -130 |
# Ou com parenteses
# dados[dados$Temperatura < (-130) |
dados[dados$Temperatura<(-130) | dados$Temperatura>130,]$Temperatura = mediana

# Verificar valores NA
dados[!complete.cases(dados$Temperatura),]
dados[is.na(dados$Temperatura)]

boxplot(dados$Temperatura, main='Temperatura', ylab='Temperatura em ºF')
hist(dados$Temperatura, main='Temperatura', xlab='Temperatura em ºF')


```



```{r}
summary(dados$Umidade)
outlies = boxplot(dados$Umidade, main='Umidade')
outlies$out
hist(dados$Umidade, main='Umidade')

# Obter Mediana
mediana = median(dados$Umidade, na.rm = T)
mediana

# Verificar dados NA
dados[!complete.cases(dados$Umidade),]
dados[is.na(dados$Umidade),]

# Tratar os dados NA 
dados[is.na(dados$Umidade),]$Umidade = mediana

dados[is.na(dados$Umidade),]

# Verificar dados fora do escopo
dados[dados$Umidade<0 | dados$Umidade>100,]

# Tratar dados fora do escopo
dados[dados$Umidade<0 | dados$Umidade>100,]$Umidade = mediana
dados[dados$Umidade<0 | dados$Umidade>100,]

summary(dados$Umidade)

boxplot(dados$Umidade)
hist(dados$Umidade)

```

# Fazer um estudo de regressão linear com Temperatura vs Umidade


```{r}
# Verificar a correlação dos dados

cor(dados[, c('Temperatura','Umidade')])
corrgram(dados[,c('Temperatura','Umidade')], order=T,
         lower.panel = panel.shade,
         upper.panel = panel.pie,
         text.panel=panel.txt,
         main='Temperatura X Umidade')


# Verificar o gráfico de dispersão com a linha de tendência
plot(dados$Umidade ~dados$Temperatura, ylab='Umidade', xlab='Temperatura', main='Dispersão Temperatura X Umidade')

modelo = lm(Umidade ~ Temperatura, data=dados)
abline(modelo)
summary(modelo)
```

```{r}
# Fazendo Previsões

umidade = predict(modelo, data.frame(Temperatura=0))
umidade
```
# Usando Navie Bayes

## Separar dados de treino

```{r}
dim(dados)
amostra = sample(2,14, replace=T, prob=c(0.7, 0.3))
amostra

jogar_treino = dados[amostra==1,]
jogar_teste = dados[amostra==2,]
jogar_teste
```
## Criar o modelo
```{r}
modelo_bayes = naiveBayes(Jogar ~ ., jogar_treino)
modelo_bayes
```
## Previsão

```{r}
previsao = predict(modelo_bayes, jogar_teste)
previsao
```
## Matriz de Confusão

```{r}
confusao = table(jogar_teste$Jogar, previsao)
confusao

taxa_acerto = (confusao[1] + confusao[4])/sum(confusao)
taxa_erro = 1 - taxa_acerto

taxa_acerto
taxa_erro
```













